### ISSUE TITLE
bug: cronjob false pass

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-spar-data#59]
This should not have passed.  :/

```
Executing in Test mode
-------------------------------------
----- ETL Tool: Unit test Execution  
-- 1. Checking if required variables are defined
-------------------------------------
Error: ORACLE_HOST environment variable is None
Traceback (most recent call last):
  File "/app/src/main.py", line 143, in <module>
    inicializa()
  File "/app/src/main.py", line 125, in inicializa
    required_variables_exists()
  File "/app/src/main.py", line 62, in required_variables_exists
    raise Exception("Not all required variables to execute a instance of Data Sync Engine exists.")
Exception: Not all required variables to execute a instance of Data Sync Engine exists.
NAME                       COMPLETIONS   DURATION   AGE
nr-spar-data-57-sync-210   0/1           [88](https://github.com/bcgov/nr-spar-data/actions/runs/8528312221/job/23361717697?pr=57#step:2:89)s        88s
Job successful!
```

**Comment by DerekRoberts** [comment]
Resolved by https://github.com/bcgov/nr-spar-data/pull/60.
